#cloud-config
hostname: splunk
ssh_pwauth: false
create_hostname_file: true
fqdn: splunk.chaos.corp
prefer_fqdn_over_hostname: false
keyboard:
  layout: us
timezone: US/Pacific
locale: en_US
allow_public_ssh_keys: true
disable_root: true
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding
disable_ec2_metadata: true
package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - unattended-upgrades
  - apt-transport-https
  - ca-certificates
  - chkrootkit
  - rkhunter
  - jq
  - curl
  - wget
  - tar
  - nginx
  - nano
  - htop
  - uuid
  - net-tools
  - dnsutils
  - openssl
  - unzip
  - gnupg
  - tree
  - cron
  - qemu-guest-agent
  - nfs-common
### USERS
ssh_import_id: ['gh:maxwelldps']
groups:
  - chaos
runcmd:
  - FALCO_FRONTEND=noninteractive FALCO_DRIVER_CHOICE=modern_ebpf apt-get install -y falco
  - falcoctl driver config --type modern_ebpf
  - systemctl enable falco
  - systemctl start falco
  - systemctl unmask falcoctl-artifact-follow.service
  - systemctl enable falcoctl-artifact-follow.service
  - mkdir -p /mnt/splunk
  - echo "10.42.0.35:/splunk /mnt/splunk nfs defaults 0 0" | tee -a /etc/fstab
  - mount -a
  - df -h
  - ln -s /opt/splunk/var/lib/splunk /mnt/splunk
  - chown -R splunk:splunk  /opt/splunk
  - ls -lash /opt/splunk/var/lib/
  - bash /opt/install-splunk.sh
  - reboot
user:
  name: professor_chaos
  shell: /bin/bash
  groups: chaos
  lock_passwd: true
  sudo: ["ALL=(ALL) NOPASSWD:ALL"]
users:
  - name: splunk
    groups: chaos
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    home: /home/splunk
    lock_passwd: false
apt:
  sources:
    falco:
      filename: falcosecurity.list
      source: deb https://download.falco.org/packages/deb stable main
      keyid: 2005399002d5e8ff59f28ce64021833e14cb7a8d
      keyserver: keyserver.ubuntu.com
write_files:
  - encoding: text/plain
    content: |
      0 * * * * /opt/chaos/scripts/chaos-x509.sh   | logger -t chaos-x509
      0 2 * * * /usr/sbin/rkhunter --check --rwo | logger -t rkhunter
      0 2 * * * /usr/sbin/chkrootkit | logger -t chkrootkit
    path: /etc/crontab
    append: true
  - encoding: text/plain
    content: |
      [chaos]

      homePath   = /mnt/splunk/chaos/db
      coldPath   = /mnt/splunk/chaos/colddb
      thawedPath = /mnt/splunk/chaos/thaweddb
      maxDataSize = 10000
      maxHotBuckets = 10
    path: /opt/splunk/etc/system/local/indexes.conf
    append: true
    defer: true
  - encoding: base64
    content: IyEvYmluL2Jhc2gKCmVjaG8gIkF0dGVtcHRpbmcgdG8gZmluZCBMVUtTIHBhcnRpdGlvbiBhdXRvbWF0aWNhbGx5Li4uIgpsdWtzX2RldmljZT0kKGxzYmxrIC1vIE5BTUUsVFlQRSxGU1RZUEUgLW5yIHwgYXdrICckMiA9PSAiY3J5cHQiIHtwcmludCAiL2Rldi8iICQxfScgfCBoZWFkIC1uIDEpCgppZiBbWyAteiAiJGx1a3NfZGV2aWNlIiBdXTsgdGhlbgogICAgZWNobyAiRXJyb3I6IE5vIExVS1MgcGFydGl0aW9uIGZvdW5kLiIKICAgIHJldHVybiAxCmZpCgplY2hvICJGb3VuZCBMVUtTIGRldmljZTogJGx1a3NfZGV2aWNlIgoKZWNobyAiQWRkaW5nIGEgbmV3IHBhc3N3b3JkIHRvIExVS1MgZGV2aWNlOiAkbHVrc19kZXZpY2UiCmNyeXB0c2V0dXAgbHVrc0FkZEtleSAiJGx1a3NfZGV2aWNlIgoKaWYgW1sgXCQ/IC1lcSAwIF1dOyB0aGVuCiAgICBlY2hvICJOZXcgTFVLUyBwYXNzd29yZCBhZGRlZCBzdWNjZXNzZnVsbHkuIgplbHNlCiAgICBlY2hvICJGYWlsZWQgdG8gYWRkIG5ldyBMVUtTIHBhc3N3b3JkLiIKICAgIHJldHVybiAxCmZpCg==
    owner: root:chaos
    path: /opt/chaos/scripts/add_luks_pw.sh
    permissions: "0o654"
    defer: true
  - encoding: base64
    content: IyEvYmluL2Jhc2gKCmVjaG8gIkZldGNoaW5nIGxhdGVzdCBDbG91ZGZsYXJlIElQIHJhbmdlcy4uLiIKQ0xPVURGTEFSRV9JUF9SQU5HRVM9JChjdXJsIC1zIGh0dHBzOi8vd3d3LmNsb3VkZmxhcmUuY29tL2lwcy12NDsgY3VybCAtcyBodHRwczovL3d3dy5jbG91ZGZsYXJlLmNvbS9pcHMtdjYpCgojIFJlbW92ZSBvbGQgQ2xvdWRmbGFyZSBJUCBydWxlcwplY2hvICJSZW1vdmluZyBvbGQgQ2xvdWRmbGFyZSBJUCBydWxlcy4uLiIKZm9yIHJ1bGUgaW4gJCh1Zncgc3RhdHVzIG51bWJlcmVkIHwgZ3JlcCAiQUxMT1cgT1VUIiB8IGdyZXAgLUUgIkNsb3VkZmxhcmUiIHwgYXdrIC1GJ1tdW10nICd7cHJpbnQgJDJ9JyB8IHNvcnQgLW5yKTsgZG8KICAgIGVjaG8gInkiIHwgdWZ3IGRlbGV0ZSAkcnVsZQpkb25lCgojIEFkZCBuZXcgQ2xvdWRmbGFyZSBJUCBydWxlcwplY2hvICJBZGRpbmcgbmV3IENsb3VkZmxhcmUgSVAgcnVsZXMuLi4iCmZvciBpcF9yYW5nZSBpbiAkQ0xPVURGTEFSRV9JUF9SQU5HRVM7IGRvCiAgICB1ZncgYWxsb3cgb3V0IHRvICIkaXBfcmFuZ2UiIGNvbW1lbnQgIkNsb3VkZmxhcmUiCmRvbmU=
    owner: root:chaos
    path: /opt/chaos/scripts/cf-ufw-rules.sh
    permissions: "0o654"
    defer: true
  - encoding: base64
    content: IyEvYmluL2Jhc2gKCiMjIyMjIERvd25sb2FkIENBIGNlcnRzIGZvciBDSEFPUyAjIyMjIyMjCgojIERpcmVjdG9yeSB0byBzdG9yZSBkb3dubG9hZGVkIGNlcnRpZmljYXRlcwpDRVJUX0RJUj0iL3Vzci9sb2NhbC9zaGFyZS9jYS1jZXJ0aWZpY2F0ZXMvY2hhb3MiCm1rZGlyIC1wICRDRVJUX0RJUgoKQ0VSVF9JTkZPX0ZJTEU9L29wdC9jaGFvcy94NTA5Ly5zcGVjdHIueWFtbAoKIyBDaGVja3MgZm9yIENBIG1ldGEgZmlsZQppZiBbWyAhIC1mICIkQ0VSVF9JTkZPX0ZJTEUiIF1dOyB0aGVuCiAgZWNobyAiWUFNTCBmaWxlIG5vdCBmb3VuZDogJENFUlRfSU5GT19GSUxFIgogIHJldHVybiAxCmZpCgojIEV4dHJhY3QgVVJMcyBmcm9tIHRoZSBZQU1MIGZpbGUgdXNpbmcgeXEKdXJscz0kKHlxIC1yICcuYWN0aXZlW10udXJsJyAiJENFUlRfSU5GT19GSUxFIikKCmZvciB1cmwgaW4gJHVybHM7IGRvCiAgZWNobyAiRG93bmxvYWRpbmcgQ0EgY2VydGlmaWNhdGUgZnJvbSAkdXJsIgogIGNlcnRfbmFtZT0kKGJhc2VuYW1lICIkdXJsIikKICBjZXJ0X3BhdGg9IiRDRVJUX0RJUi8kY2VydF9uYW1lIgoKICAjIERvd25sb2FkIHRoZSBjZXJ0aWZpY2F0ZQogIGlmIGN1cmwgLXNTTCAtbyAiJGNlcnRfcGF0aCIgJHVybDsgdGhlbgogICAgZWNobyAiU3VjY2Vzc2Z1bGx5IGRvd25sb2FkZWQgJGNlcnRfbmFtZSIKICBlbHNlCiAgICBlY2hvICJGYWlsZWQgdG8gZG93bmxvYWQgJHVybCIKICAgIGNvbnRpbnVlCiAgZmkKZG9uZQoKIyBVcGRhdGUgdGhlIENBIGNlcnRpZmljYXRlcwp1cGRhdGUtY2EtY2VydGlmaWNhdGVzCg==
    owner: root:chaos
    path: /opt/chaos/scripts/chaos-x509.sh
    permissions: "0o654"
    defer: true
  - encoding: base64
    content: IyEvYmluL2Jhc2gKCiMgUmVhZCBpbnB1dCBmcm9tIHN0ZGluCmlucHV0PSQoY2F0KQpsb2dfanNvbj0kKGVjaG8gIiRpbnB1dCIgfCBqcSAtLWFyZyBob3N0bmFtZSAiYGhvc3RuYW1lYCIgJy4gfCB7aG9zdDogJGhvc3RuYW1lLCBzb3VyY2V0eXBlOiAiZmFsY28iLCBpbmRleDogImZhbGNvIiwgZXZlbnQ6IC59JykKCmN1cmwgLWsgLWQgIiRsb2dfanNvbiIgXAogICAgLUggIkF1dGhvcml6YXRpb246IFNwbHVuayBQT1RBVE8iIFwKICAgICJodHRwczovL3NwbHVuay5jaGFvcy5jb3JwOjgwODgvc2VydmljZXMvY29sbGVjdG9yL2V2ZW50Ig==
    owner: root:chaos
    path: /opt/chaos/scripts/log_hec.sh
    permissions: "0o654"
    defer: true
  - encoding: base64
    content: "bG9hZF9wbHVnaW5zOiBbXQoKcnVsZV9tYXRjaGluZzogYWxsCmxvZ19zdGRlcnI6IHRydWUKbG9nX3N5c2xvZzogdHJ1ZQoKanNvbl9vdXRwdXQ6IHRydWUKanNvbl9pbmNsdWRlX291dHB1dF9wcm9wZXJ0eTogdHJ1ZQpqc29uX2luY2x1ZGVfbWVzc2FnZV9wcm9wZXJ0eTogdHJ1ZQoKZW5naW5lOgogIGtpbmQ6IG1vZGVybl9lYnBmCgpzdGRvdXRfb3V0cHV0OgogIGVuYWJsZWQ6IHRydWUKCnN5c2xvZ19vdXRwdXQ6CiAgZW5hYmxlZDogdHJ1ZQoKZmlsZV9vdXRwdXQ6CiAgZW5hYmxlZDogZmFsc2UKICBrZWVwX2FsaXZlOiBmYWxzZQogIGZpbGVuYW1lOiAvdmFyL2xvZy9mYWxjby9mYWxjby5sb2cKCnByb2dyYW1fb3V0cHV0OgogIGVuYWJsZWQ6IHRydWUKICBwcm9ncmFtOiAgL29wdC9jaGFvcy9zY3JpcHRzL2xvZ19oZWMuc2g="
    owner: root:chaos
    path: /etc/falco/config.d/01-chaos.yaml
    permissions: "0o654"
    defer: true
  - encoding: base64
    defer: true
    content: IyEvYmluL2Jhc2gKCiMgVmFyaWFibGVzClNQTFVOS19VU0VSPSJzcGx1bmsiCklOU1RBTExfRElSPSIvb3B0L3NwbHVuayIKCkRPTUFJTl9OQU1FPXNwbHVuay5jaGFvcy5jb3JwICMgUmVwbGFjZSB3aXRoIHlvdXIgZG9tYWluCkNFUlRfUEFUSD0iL29wdC9jaGFvcy9zc2wvc3BsdW5rLmNydCIgICMgUmVwbGFjZSB3aXRoIHlvdXIgY2VydGlmaWNhdGUgcGF0aApDRVJUX0tFWV9QQVRIPSIvb3B0L2NoYW9zL3NzbC9zcGx1bmsua2V5IiAgIyBSZXBsYWNlIHdpdGggeW91ciBwcml2YXRlIGtleSBwYXRoCgoKZG93bmxvYWRfc3BsdW5rKCkgewogICAgZWNobyAiRG93bmxvYWRpbmcgU3BsdW5rLi4uIgogICAgd2dldCAtTyAvdG1wL3NwbHVuay05LjMuMi1kOGJiMzI4MDk0OTgtbGludXgtMi42LWFtZDY0LmRlYiBodHRwczovL2Rvd25sb2FkLnNwbHVuay5jb20vcHJvZHVjdHMvc3BsdW5rL3JlbGVhc2VzLzkuMy4yL2xpbnV4L3NwbHVuay05LjMuMi1kOGJiMzI4MDk0OTgtbGludXgtMi42LWFtZDY0LmRlYgogICAgd2dldCAtTyAvdG1wL3NwbHVuay05LjMuMi1kOGJiMzI4MDk0OTgtbGludXgtMi42LWFtZDY0LmRlYi5zaGE1MTIgaHR0cHM6Ly9kb3dubG9hZC5zcGx1bmsuY29tL3Byb2R1Y3RzL3NwbHVuay9yZWxlYXNlcy85LjMuMi9saW51eC9zcGx1bmstOS4zLjItZDhiYjMyODA5NDk4LWxpbnV4LTIuNi1hbWQ2NC5kZWIuc2hhNTEyIAogICAgc2hhNTEyc3VtIC1jIC90bXAvc3BsdW5rLTkuMy4yLWQ4YmIzMjgwOTQ5OC1saW51eC0yLjYtYW1kNjQuZGViLnNoYTUxMgogICAgZHBrZyAtaSAvdG1wL3NwbHVuay05LjMuMi1kOGJiMzI4MDk0OTgtbGludXgtMi42LWFtZDY0LmRlYgoKfQpzdGFydF9zcGx1bmtfc2VydmljZSgpIHsKICAgIGVjaG8gIkVuYWJsaW5nIFNwbHVuayBzZXJ2aWNlLi4uIgogICAgc3VkbyAtdSAkU1BMVU5LX1VTRVIgJElOU1RBTExfRElSL2Jpbi9zcGx1bmsgc3RhcnQgLS1hY2NlcHQtbGljZW5zZSAtLWFuc3dlci15ZXMgLS1uby1wcm9tcHQgLS1zZWVkLXBhc3N3ZCAKICAgICRJTlNUQUxMX0RJUi9iaW4vc3BsdW5rIGVuYWJsZSBib290LXN0YXJ0IC11c2VyICRTUExVTktfVVNFUgp9CgojIGJhc2ljX2hhcmRlbmluZygpIHsKIyAgICAgZWNobyAiQXBwbHlpbmcgYmFzaWMgaGFyZGVuaW5nLi4uIgojICAgICBzdWRvIC11ICRTUExVTktfVVNFUiAkSU5TVEFMTF9ESVIvYmluL3NwbHVuayBzZXQgd2ViLXNzbCBlbmFibGUKIyAgICAgc3VkbyAtdSAkU1BMVU5LX1VTRVIgJElOU1RBTExfRElSL2Jpbi9zcGx1bmsgc2V0IG1pbmZyZWVtYiA1MDAKIyAgICAgc3VkbyAtdSAkU1BMVU5LX1VTRVIgJElOU1RBTExfRElSL2Jpbi9zcGx1bmsgc2V0IHNlcnZlcm5hbWUgJERPTUFJTl9OQU1FCiMgICAgICMgT3B0aW9uYWw6IFNldCB1cCBhIGN1c3RvbSBhZG1pbiBwYXNzd29yZAojIH0KCmNvbmZpZ3VyZV9uZ2lueF9wcm94eSgpIHsKCQlta2RpciAtcCBgZGlybmFtZSAkQ0VSVF9LRVlfUEFUSGAKCiAgICBvcGVuc3NsIGVjcGFyYW0gLWdlbmtleSAtbmFtZSBzZWNwMzg0cjEgLW91dCAkQ0VSVF9LRVlfUEFUSAogICAgb3BlbnNzbCByZXEgLW5ldyAteDUwOSAtZGF5cyA0MjAgXAogICAgICAgIC1rZXkgJENFUlRfS0VZX1BBVEggXAogICAgICAgIC1vdXQgJENFUlRfUEFUSCBcCiAgICAgICAgLXN1YmogIi9DPVVTL1NUPVlFUy9MPVNVUkUvTz1DSEFPUy9PVT1ZRVMvQ049JERPTUFJTl9OQU1FIgoKICAgIGVjaG8gIkNvbmZpZ3VyaW5nIE5naW54IGFzIGEgcmV2ZXJzZSBwcm94eSB3aXRoIFNTTC4uLiIKICAgICMgQ3JlYXRlIE5naW54IGNvbmZpZyBmaWxlIGZvciBTcGx1bmsKICAgIGNhdCA8PC1FT0wgPiAvZXRjL25naW54L3NpdGVzLWF2YWlsYWJsZS9zcGx1bmsKCQlzZXJ2ZXIgewoJCQkJbGlzdGVuIDgwOwoJCQkJc2VydmVyX25hbWUgJERPTUFJTl9OQU1FOwoKCQkJCSMgUmVkaXJlY3QgYWxsIEhUVFAgdHJhZmZpYyB0byBIVFRQUwoJCQkJbG9jYXRpb24gLyB7CgkJCQkJCXJldHVybiAzMDEgaHR0cHM6Ly9cJGhvc3RcJHJlcXVlc3RfdXJpOwoJCQkJfQoJCX0KCgkJc2VydmVyIHsKCQkJCWxpc3RlbiA0NDMgc3NsOwoJCQkJc2VydmVyX25hbWUgJERPTUFJTl9OQU1FOwoKCQkJCSMgU1NMIGNvbmZpZ3VyYXRpb24KCQkJCXNzbF9jZXJ0aWZpY2F0ZSAkQ0VSVF9QQVRIOwoJCQkJc3NsX2NlcnRpZmljYXRlX2tleSAkQ0VSVF9LRVlfUEFUSDsKCgkJCQkjIFNTTCBwYXJhbWV0ZXJzCgkJCQlzc2xfcHJvdG9jb2xzIFRMU3YxLjIgVExTdjEuMzsKCQkJCXNzbF9jaXBoZXJzIEhJR0g6IWFOVUxMOiFNRDU7CgkJCQlzc2xfcHJlZmVyX3NlcnZlcl9jaXBoZXJzIG9uOwoKCQkJCSMgUHJveHkgY29uZmlndXJhdGlvbgoJCQkJbG9jYXRpb24gLyB7CgkJCQkJCXByb3h5X3Bhc3MgaHR0cDovL2xvY2FsaG9zdDo4MDAwOwoJCQkJCQlwcm94eV9zZXRfaGVhZGVyIEhvc3QgXCRob3N0OwoJCQkJCQlwcm94eV9zZXRfaGVhZGVyIFgtUmVhbC1JUCBcJHJlbW90ZV9hZGRyOwoJCQkJCQlwcm94eV9zZXRfaGVhZGVyIFgtRm9yd2FyZGVkLUZvciBcJHByb3h5X2FkZF94X2ZvcndhcmRlZF9mb3I7CgkJCQkJCXByb3h5X3NldF9oZWFkZXIgWC1Gb3J3YXJkZWQtUHJvdG8gaHR0cHM7CgkJCQl9CgkJfQoJCUVPTAoKICAgICMgRW5hYmxlIHRoZSBTcGx1bmsgc2l0ZSBhbmQgcmVsb2FkIE5naW54CiAgICBsbiAtcyAvZXRjL25naW54L3NpdGVzLWF2YWlsYWJsZS9zcGx1bmsgL2V0Yy9uZ2lueC9zaXRlcy1lbmFibGVkLwogICAgc3lzdGVtY3RsIHJlbG9hZCBuZ2lueAp9CgoKZG93bmxvYWRfc3BsdW5rCgpzdGFydF9zcGx1bmtfc2VydmljZQoKY29uZmlndXJlX25naW54X3Byb3h5CgplY2hvICJTcGx1bmsgaW5zdGFsbGF0aW9uIGFuZCBiYXNpYyBoYXJkZW5pbmcgY29tcGxldGVkIHdpdGggTmdpbnggcHJveHkgb24gcG9ydCA0NDMhIgplY2hvICJBY2Nlc3MgU3BsdW5rIFdlYiBhdCBodHRwczovLyRET01BSU5fTkFNRSIK
    owner: root:chaos
    path: /opt/install-splunk.sh
    permissions: "0o654"
ca_certs:
  remove_defaults: false
  trusted:
    - |-
      -----BEGIN CERTIFICATE-----
      MIIDLTCCArOgAwIBAgIIJEOUNshbVgIwCgYIKoZIzj0EAwMwgYQxCzAJBgNVBAYT
      AktaMQ0wCwYDVQQIEwRXRVNUMSAwHgYDVQQHExdEci4gRXZpbHMgVm9sY2FubyBM
      YXllcjETMBEGA1UEChMKQ0hBT1MuQ09SUDEYMBYGA1UECxMPQ0hBT1RJQyBGQUNU
      T1JTMRUwEwYDVQQDEwxjaGFvcy5jb20uY28wHhcNMjQwNDIwMTIxNTAwWhcNMzUw
      NjA5MTIxNTAwWjCBhDELMAkGA1UEBhMCS1oxDTALBgNVBAgTBFdFU1QxIDAeBgNV
      BAcTF0RyLiBFdmlscyBWb2xjYW5vIExheWVyMRMwEQYDVQQKEwpDSEFPUy5DT1JQ
      MRgwFgYDVQQLEw9DSEFPVElDIEZBQ1RPUlMxFTATBgNVBAMTDGNoYW9zLmNvbS5j
      bzB2MBAGByqGSM49AgEGBSuBBAAiA2IABIt5UvVcp9mTmq7b9u54z75JltyfDe8q
      1g5OPlhzfUaNJtupGtaDI9u7aA9Eyfkkjns7V8CZBJVxuUoqdgRkZKdkL+sY3Cws
      bRqWGCBHtgJPyDNEUx+2/lnz+Rw1h60a9aOB7zCB7DAPBgNVHRMBAf8EBTADAQH/
      MB0GA1UdDgQWBBRxbxzzRp0uPniagqn3sjwojdMaZzALBgNVHQ8EBAMCAQYwFwYD
      VR0RBBAwDoIMY2hhb3MuY29tLmNvMIGTBgNVHR8EgYswgYgwLKAqoCiGJmh0dHBz
      Oi8vY2FuYXJ5LmNoYW9zLmNvbS5jby9yaXAtYS1yb25pMCmgJ6AlhiNodHRwczov
      L3JpcC5jaGFvcy5jb20uY28vcmlwLWEtcm9uaTAtoCugKYYnaHR0cHM6Ly95ZWV0
      Lmt1YmVkZXN0cnllci5pby9yaXAtYS1yb25pMAoGCCqGSM49BAMDA2gAMGUCMQDM
      lyT2f3+LYEIdAT2ElDh7rLMfEMKbayvxZmPRYIuPdYJ4RMlKwtWWkF0vgnUErakC
      MACZqm/38iakwO0iY+rSu35ibgIdBP6MyX+dJt1aU0EIPfeBAdEFUG6Z8de+wwf0
      7g==
      -----END CERTIFICATE-----
    - |-
      -----BEGIN CERTIFICATE-----
      MIIDLTCCArOgAwIBAgIIJdYRA8JQQaswCgYIKoZIzj0EAwIwgYQxCzAJBgNVBAYT
      AktaMQ0wCwYDVQQIEwRXRVNUMSAwHgYDVQQHExdEci4gRXZpbHMgVm9sY2FubyBM
      YXllcjETMBEGA1UEChMKQ0hBT1MuQ09SUDEYMBYGA1UECxMPQ0hBT1RJQyBGQUNU
      T1JTMRUwEwYDVQQDEwxjaGFvcy5jb20uY28wHhcNMjQwNDIwMTIxNTAwWhcNMzUw
      NjA5MTIxNTAwWjCBhDELMAkGA1UEBhMCS1oxDTALBgNVBAgTBFdFU1QxIDAeBgNV
      BAcTF0RyLiBFdmlscyBWb2xjYW5vIExheWVyMRMwEQYDVQQKEwpDSEFPUy5DT1JQ
      MRgwFgYDVQQLEw9DSEFPVElDIEZBQ1RPUlMxFTATBgNVBAMTDGNoYW9zLmNvbS5j
      bzB2MBAGByqGSM49AgEGBSuBBAAiA2IABFsGNcgxRCaT2SOfH1ioJTmXdi5QZd9M
      UXmopgC7Ifs6ZXQ6ygJsWoKul21UkulGYn6ooFnTNgez48FWCWGTgsyEPDm3ork2
      ANZRVie6ro4tsvhZj4MKTrdLS5y2wq4EOaOB7zCB7DAPBgNVHRMBAf8EBTADAQH/
      MB0GA1UdDgQWBBRzFvwll2NJgzF7dMWTFighOCaHQDALBgNVHQ8EBAMCAQYwFwYD
      VR0RBBAwDoIMY2hhb3MuY29tLmNvMIGTBgNVHR8EgYswgYgwLKAqoCiGJmh0dHBz
      Oi8vY2FuYXJ5LmNoYW9zLmNvbS5jby9yaXAtYS1yb25pMCmgJ6AlhiNodHRwczov
      L3JpcC5jaGFvcy5jb20uY28vcmlwLWEtcm9uaTAtoCugKYYnaHR0cHM6Ly95ZWV0
      Lmt1YmVkZXN0cnllci5pby9yaXAtYS1yb25pMAoGCCqGSM49BAMCA2gAMGUCMGwh
      fMlrLvTUkKqXYd9Adifmng+3/E+3HG0Mz19rZOT2e1XrGyVSif+3JUVCguSALgIx
      AMeecZp0/nMkgICXL9UVX7IQmBVFcIy+ZwBGOpd/FxSZN5s0g/9EuLux3OJlfnO1
      nA==
      -----END CERTIFICATE-----
    - |-
      -----BEGIN CERTIFICATE-----
      MIICfDCCAgKgAwIBAgIISGoqJAO0KR0wCgYIKoZIzj0EAwMwgYQxCzAJBgNVBAYT
      AktaMQ0wCwYDVQQIEwRXRVNUMSAwHgYDVQQHExdEci4gRXZpbHMgVm9sY2FubyBM
      YXllcjETMBEGA1UEChMKQ0hBT1MuQ09SUDEYMBYGA1UECxMPQ0hBT1RJQyBGQUNU
      T1JTMRUwEwYDVQQDEwxjaGFvcy5jb20uY28wHhcNMjQwODExMTIyMjAwWhcNMzQw
      ODExMTIyMjAwWjCBhDELMAkGA1UEBhMCS1oxDTALBgNVBAgTBFdFU1QxIDAeBgNV
      BAcTF0RyLiBFdmlscyBWb2xjYW5vIExheWVyMRMwEQYDVQQKEwpDSEFPUy5DT1JQ
      MRgwFgYDVQQLEw9DSEFPVElDIEZBQ1RPUlMxFTATBgNVBAMTDGNoYW9zLmNvbS5j
      bzB2MBAGByqGSM49AgEGBSuBBAAiA2IABOQeteKy7L9B38ENirwIuUxwOoh4ndPW
      ykpC9+at1JldzePyXngcn/ppc1NeXsmfFb78El4FBR8LZlYwGDHR0hlETLVJewjz
      ItuFKr7WJq7ffHWQPDWfXBr6rkKlK84TPKM/MD0wDwYDVR0TAQH/BAUwAwEB/zAd
      BgNVHQ4EFgQUYoo+wWwTCwJ10G1jqh+4qknewjowCwYDVR0PBAQDAgEGMAoGCCqG
      SM49BAMDA2gAMGUCMQCoojR6x5olK1K+ozXzlP7JY4ldvwhh4DfEYQZFwQX2Oa8L
      XccuwlG3Am17MlsRQzsCMFxWji/QXhdp8zcfOztygP70eLO8a4DTzRQyINF4lkBo
      RWNj4CdfFKklI4uZp1yU0A==
      -----END CERTIFICATE-----
